[package]
name = "cw3-archway"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>", "FÃ¡bio Soares <fsoares.developer@gmail.com>"]
edition = "2021"
description = "CosmWasm-3 Interface: On-Chain MultiSig/Voting contracts, with Archway integration"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cw-utils = "1.0.1"
cw20 = "1.0.1"
cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
archway-bindings = { version = "0.1.0", git = "https://github.com/FSoaresDev/archway-bindings", branch = "update-bindings-issue-10" }
